# Generated by Django 4.1.5 on 2023-01-11 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=5)),
                ('documento', models.IntegerField(unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('hobbie', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'enersinc_persona',
            },
        ),
    ]
